Vagrant.configure(2) do |config|
  vm_name = "emberjs-todomvc"
  vm_name ||= Pathname.new(Dir.getwd).basename.to_s
  config.vm.synced_folder "archive/", "/var/cache/apt/archives", create: true
  config.vm.box = "anthshor/ubuntu14042-emberjs1131"
  config.vm.provider :virtualbox do |vb|
    vb.name=vm_name
    vb.customize ['modifyvm', :id, '--memory', '2048']
  end
  config.vm.hostname=vm_name
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.network "forwarded_port", guest: 4200, host: 8080
  config.vm.network "forwarded_port", guest: 4200, host: 8888
  config.vm.provision "shell", privileged: false, path: "provision.sh", args: "N"
end	
